accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
 
]

chatting/urls.py
# your_app/urls.py
from django.urls import path
from . import views
app_name='chatting'
urlpatterns = [
    path('<str:origin_user_id>/<str:otheruser_id>', views.create_room, name='create_room'),
    path('<str:room_name>/<str:origin_user_id>/<str:otheruser_id>', views.chat_room, name='chat_room'),
]

core/urls.py
from django.urls import path
from . import views
app_name='core'
urlpatterns = [
    path('', views.index, name='index'),
   
 
]

northproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('chat/',include("chatting.urls")),
    path('',include('core.urls')),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
]

chatting/models.py
from django.contrib.auth.models import User
from django.db import models



class ChatThread(models.Model):
    room_name = models.CharField(max_length=500)
    origin_user = models.IntegerField()
    other_user = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        unique_together = ('origin_user', 'other_user')

    # def __str__(self):
    #     return f"Chat between {self.alpha_user.username} and {self.beta_user.username}"

class ChatText(models.Model):
    thread = models.ForeignKey(ChatThread, related_name='messages', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return f"Message from {self.sender.username} at {self.timestamp}"

core/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label='Username',widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
        widgets ={
                'username':forms.TextInput(attrs={'class':'form-control '}),
                'first_name':forms.TextInput(attrs={'class':'form-control'}),
                'email':forms.TextInput(attrs={'class':'form-control'}),
            }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].label = "Full Name"  # Custom label
        self.fields['username'].help_text = "[alphanumeric, words @, #, $, %, &.]" 
        
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from django.http import request
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm                                       
from django.contrib import auth, messages
from .forms import LoginForm, UserRegistrationForm
from django.http.response import HttpResponseRedirect
from django.template.context import RequestContext
from django.urls import reverse
from django.contrib.auth import logout as auth_logout

def user_logout(request):
    auth_logout(request)  # Call Django's built-in logout function
    return redirect("core:index")


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                        username=cd['username'],
                                        password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("core:index")
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid ():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            user = authenticate(request, username=user_form.cleaned_data['username'], password=user_form.cleaned_data['password'])
            if user is not None:
                login(request, user)
            return redirect("core:index")
    else:
        user_form = UserRegistrationForm()
    return render(request,'accounts/register.html',{'user_form': user_form})

chatting/views.py
from django.shortcuts import render
# Create your views here.
# your_app/views.py
from django.shortcuts import render,redirect
from .models import ChatThread,  ChatText
import uuid
import shortuuid
from django.contrib.auth.models import User
from django.urls import reverse
#single person chat
from django.shortcuts import redirect
from django.urls import reverse
from django.db import IntegrityError
from django.db.models import Q

def create_room(request, origin_user_id, otheruser_id):
    try:
        # Generate a unique room name
        room_uuid = shortuuid.uuid()
        room_name = f"room_{room_uuid}{origin_user_id}{otheruser_id}"
        
        # Attempt to create a new ChatThread
        room = ChatThread.objects.create(
            room_name=room_name,
            origin_user=origin_user_id,
            other_user=otheruser_id
        )
    except IntegrityError:
        # Handle the case where the unique constraint is violated
        room = ChatThread.objects.filter(
            Q(origin_user=origin_user_id, other_user=otheruser_id) |
            Q(origin_user=otheruser_id, other_user=origin_user_id)
        ).filter(active=True).first()
        
        if room:
            # If an active room exists, redirect to it
            room_name = room.room_name
        else:
            # If no active room exists, activate an existing one
            room = ChatThread.objects.filter(
                Q(origin_user=origin_user_id, other_user=otheruser_id) |
                Q(origin_user=otheruser_id, other_user=origin_user_id)
            ).first()
            room.active = True
            room.save()
            room_name = room.room_name

    # Redirect to the appropriate chat room
    url = reverse('chatting:chat_room', kwargs={
        'room_name': room_name,
        'origin_user_id': origin_user_id,
        'otheruser_id': otheruser_id
    })
    return redirect(url)



def chat_room(request, room_name, origin_user_id, otheruser_id):
    return render(request, 'chat.html', {
        'room_name': room_name,
        #'otheruser':otheruser
    })

core/views.py
from django.shortcuts import render
import uuid;
# Create your views here.
from django.contrib.auth.models import User
from chatting.models import ChatThread, ChatText
from django.db.models import Q
def index(request):
    logged_user_id = request.user.id
    current_rooms = ChatThread.objects.filter(
    Q(origin_user=logged_user_id) | Q(other_user=logged_user_id))
    auth_user = User.objects.exclude(id=logged_user_id)
    testroom = uuid.uuid4().hex
    context = {
        'auth_user':auth_user,
        'testroom':testroom,
        'active_rooms':current_rooms,
    }
    return render(request, "index.html", context)

templates/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
      body{
        background-color:gray!important;
      }
    </style>
  </head>
  <body>
   {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/accounts/login.html
{% extends "accounts/base.html" %}

{% block content %}

<div class="">

    <!--Login Form Start Here-->
    <form method="post" class="fs-5 bg-body-tertiary p-4 shadow mb-5 rounded" style="width: 350px; height: 25%; margin: 0 auto; margin-top: 10%; background-color: #f4f4f9;">
        {{ form.as_p }}
        {% csrf_token %}
        <div class="form-check mt-3">
            <input type="checkbox" class="form-check-input" id="rememberMe">
            <label class="form-check-label" for="rememberMe">Remember Me</label>
        </div>
        <p><input type="submit" class="btn btn-warning btn-md mt-4 w-100 rounded" value="Log in"></p>
        <div class="bottom-links mt-3 fs-6">
            <a href="#" style="color: #007bff;">Forgot Password?</a> | 
            <a href="{% url "accounts:register" %}" style="color: #007bff;">Do not have account yet?</a>
        </div>
    </form>
    <a href="{% url "core:index" %}" class="btn btn-primary m-4 ">Back Home </a>  
    <div> 
{% endblock content %}

templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block title %}<title>Sign-up</title>{% endblock %}
{% block content %}
<div class="">
    <div class="fs-5 bg-body-tertiary shadow rounded px-3 py-1 mb-1 text-center"style="width: 450px; height: 25%; margin: 0 auto; margin-top: 10%; background-color: #f4f4f9;"><h4>Create an account</h4></div>
 <!--Login Form Start Here-->
 <form method="post" class="fs-5 bg-body-tertiary p-4 shadow mb-5 rounded fs-6" style="width: 450px; height: 25%; margin: 0 auto; background-color: #f4f4f9;">
    {{ user_form.as_p }}
    {% csrf_token %}
    <div class="form-check mt-3">
        <input type="checkbox" class="form-check-input" id="rememberMe">
        <label class="form-check-label" for="rememberMe">Remember Me</label>
    </div>
    <p><input type="submit" class="btn btn-warning btn-md mt-4 w-100 rounded" value="Submit"></p>
    <div class="bottom-links mt-3 fs-6">
        
        <a href="{% url "accounts:login" %}" style="color: #007bff;">Already have account? login</a>
    </div>
</form>
<a href="{% url "core:index" %}" class="btn btn-primary m-4 ">Back Home </a>  
 <div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}{% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% include "depen/stylecdn.html" %}
  </head>
  <body>
    {% include "includes/navbar.html" %}
    <div class="row container">
      <!-- Left Sidebar -->
      <div class="col-2">
       

        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
          Toggle width collapse
        </button>

        <div style="min-height: 120px;">
          <div class="collapse collapse-horizontal" id="collapseWidthExample">
             {% if request.user.is_authenticated %}
            <div class="card card-body" style="width: fit-content">
             
              <ul class="" >
                {% if auth_user %}
                {% for auth_user in auth_user  %}
                <li class="list-group-item"><a href="{% url 'chatting:create_room' origin_user_id=request.user.id otheruser_id=auth_user.id %}">
                  {{ auth_user.username }}
              </a>
              </li>
                {% endfor %}
                {% else %}
                {% endif %}
              </ul>
            </div>
            {% endif %}
          </div>
        </div>

      </div>
    
      <!-- Main Content -->
      <div class="col-8">
        <main>
          {% block content %}{% endblock content %}
        </main>
      </div>
    
      <!-- Right Sidebar -->
      <div class="col-2">
        Right Side
      </div>
    </div>
    
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/chat.html
{% extends "base.html" %}
{% block title %}
<title>Chat Room</title>
{% endblock title %}

{% block content %}
<div class="container">
    <textarea id="chat-log" cols="100" rows="20" readonly></textarea><br />
    <input id="chat-message-input" type="text" size="100" />
    <button id="chat-message-submit">Send</button>
</div>

<script>
    // Extract the room name from the URL
    const roomName = window.location.pathname.split("/")[2];

    // WebSocket connection
    const chatSocket = new WebSocket(
        "ws://" + window.location.host + "/ws/chat/" + roomName + "/"
    );

    chatSocket.onopen = function () {
        console.log("WebSocket connection established.");
    };

    chatSocket.onclose = function () {
        console.log("WebSocket connection closed.");
    };

    document.querySelector("#chat-message-submit").onclick = function () {
        const messageInput = document.querySelector("#chat-message-input").value.trim();
        if (messageInput) {
            chatSocket.send(
                JSON.stringify({
                    message: messageInput,
                    username: "{{ request.user.username }}",
                })
            );
            document.querySelector("#chat-message-input").value = "";
        }
    };

    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        const chatLog = document.querySelector("#chat-log");
        chatLog.value += `${data.username}: ${data.message}\n`;
        chatLog.scrollTop = chatLog.scrollHeight;
    };
</script>

{% endblock content %}

templates/depen/stylecdn.html
<link rel="stylesheet" href="https://cdn.lineicons.com/5.0/lineicons.css" />

templates/includes/navbar.html
<nav class="navbar sticky-top  navbar-expand-lg bg-body-tertiary shadow-sm px-2 py-3 ">
    <div class="container-fluid d-flex justify-content-between">
      <!-- Left side: Button -->
      <a class="fs-3 fw-semibold" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample" style="color: inherit; text-decoration: none;">
        <i class="lni lni-menu-hamburger-1"></i>
      </a>
     
      
      <!-- Right side: Navbar links -->
      <div class="d-flex align-items-center">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active me-4" aria-current="page" href="{% url "core:index" %}">Home</a>
            <a class="nav-link me-4" href="#">Features</a>
            <a class="nav-link me-4" href="#">Pricing</a>
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </div>
        </div>
      </div>
    </div>
  </nav>

  {% include "includes/user_menu.html" %}

templates/includes/user_menu.html
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">90north</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body d-flex flex-column" style="height: 100vh;">
    {% if request.user.is_authenticated %}
      <h4>Welcome, {{ request.user.username }}</h4>
      <div class="col-auto">
        <a href="{% url 'accounts:logout' %}" class="btn bg-body-secondary">Logout</a>
      </div>
      {% else %}
       <div class="row d-flex justify-content-between">
      <div class="col-auto">
        <a href="{% url 'accounts:register' %}" class="btn btn-warning">Signup</a>
      </div>
      <div class="col-auto">
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
      </div>
    </div>
    {% endif %}
  
    
    <!-- Copyright Footer -->
    <div class="mt-auto text-center py-3">
      <small>&copy; 2025 90north. All Rights Reserved.</small>
    </div>
  </div>
</div>

templates/index.html
{% extends "base.html" %}
{% block title %}
<title>Home</title>
{% endblock title %}
{% block content %}

<div class="container m-4 ">
  <h4>Active Chats</h4>
    <ul class="list-group">
        {% for room in active_rooms %}
          <li class="list-group-item d-flex flex-row justify-content-around">
            <a href="{% url 'chatting:chat_room' room_name=room.room_name origin_user_id=room.origin_user otheruser_id=room.other_user %}">Join Now</a>
          </li>
        {% endfor %}
      </ul>
      
   
</div>
{% endblock content %}